version: "2"
services:
# for docker hub ci
  sut:
    build: .
    volumes:
      - "./test:/opt/resource/test"
      - "./package.json:/opt/resource/package.json"
    command: sh -c "apk add --no-cache npm; npm install; npm test"
# for interactive testing
  test:
    build: .
    volumes:
      - "./test:/opt/resource/test"
      - "./index.js:/opt/resource/index.js"
      - "./lib:/opt/resource/lib"